AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

ConditionalAssignment:
  Enabled: false
StringLiterals:
   EnforcedStyle: double_quotes
RedundantReturn:
  Enabled: false
# Style/Documentation:
#   Enabled: false
WordArray:
  Enabled: false
AbcSize:
  Enabled: false
MutableConstant:
  Enabled: false
SignalException:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
MissingRespondToMissing:
  Enabled: false
  Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 150
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false